### ISSUE TITLE
Socket failure at MESSAGE(Cannot decrypt message: no suitable session found)

### ISSUE THREAD

**Issue by GDB4J** [Auties00/WhatsappWeb4j#146]
@Auties00 
Probly a duplicate of https://github.com/Auties00/WhatsappWeb4j/issues/143

```
2022-06-26 22:26:39,207 |  WARN | Grizzly(1) | it.auties.whatsapp.binary.Socket | Socket failure at MESSAGE(Cannot decrypt message: no suitable session found)
2022-06-26 22:26:39,208 |  WARN | Grizzly(1) | it.auties.whatsapp.binary.Socket | Saved stacktrace at: /home/user/.whatsappweb4j/exceptions/1656275199207.txt
2022-06-26 22:26:39,208 |  WARN | Grizzly(1) | it.auties.whatsapp.binary.Socket | Ignoring failure
```

Stacktrace:
```
java.util.NoSuchElementException: Cannot decrypt message: no suitable session found
	at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:146)
	at it.auties.whatsapp.binary.Socket$MessageHandler.decode(Socket.java:1387)
	at it.auties.whatsapp.binary.Socket$MessageHandler.decode(Socket.java:1324)
	at it.auties.whatsapp.binary.Socket$MessageHandler.lambda$decode$34(Socket.java:1273)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.binary.Socket$MessageHandler.decode(Socket.java:1273)
	at it.auties.whatsapp.binary.Socket$StreamHandler.digest(Socket.java:565)
	at it.auties.whatsapp.binary.Socket.handleNode(Socket.java:203)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.binary.Socket.onBinary(Socket.java:198)
	at jdk.internal.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:560)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
	at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Key used already or never filled
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at it.auties.whatsapp.util.Validate.createThrowable(Validate.java:29)
	at it.auties.whatsapp.util.Validate.isTrue(Validate.java:14)
	at it.auties.whatsapp.util.Validate.isTrue(Validate.java:9)
	at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:166)
	at it.auties.whatsapp.crypto.SessionCipher.tryDecrypt(SessionCipher.java:152)
	at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:131)
	... 38 more

```

These exceptions are coming "randomly" in the application log.
Not that big of an issue but:
- is it possible to fix this or how can I fix it?
- Is there a way it is no longer written to a file, as this take unnecessary diskspace after a while?
- Can we configure the way exceptions are treated?

Setup
- Spring boot 2.6.6
- JDK 17.0.2
- whatsappweb4j 3.0-RC11

_#Priority: Low_

**Comment by Auties00** [comment]
> @Auties00 Probly a duplicate of #143
> 
> ```
> 2022-06-26 22:26:39,207 |  WARN | Grizzly(1) | it.auties.whatsapp.binary.Socket | Socket failure at MESSAGE(Cannot decrypt message: no suitable session found)
> 2022-06-26 22:26:39,208 |  WARN | Grizzly(1) | it.auties.whatsapp.binary.Socket | Saved stacktrace at: /home/user/.whatsappweb4j/exceptions/1656275199207.txt
> 2022-06-26 22:26:39,208 |  WARN | Grizzly(1) | it.auties.whatsapp.binary.Socket | Ignoring failure
> ```
> 
> Stacktrace:
> 
> ```
> java.util.NoSuchElementException: Cannot decrypt message: no suitable session found
> 	at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:146)
> 	at it.auties.whatsapp.binary.Socket$MessageHandler.decode(Socket.java:1387)
> 	at it.auties.whatsapp.binary.Socket$MessageHandler.decode(Socket.java:1324)
> 	at it.auties.whatsapp.binary.Socket$MessageHandler.lambda$decode$34(Socket.java:1273)
> 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
> 	at it.auties.whatsapp.binary.Socket$MessageHandler.decode(Socket.java:1273)
> 	at it.auties.whatsapp.binary.Socket$StreamHandler.digest(Socket.java:565)
> 	at it.auties.whatsapp.binary.Socket.handleNode(Socket.java:203)
> 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
> 	at it.auties.whatsapp.binary.Socket.onBinary(Socket.java:198)
> 	at jdk.internal.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
> 	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652)
> 	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:560)
> 	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800)
> 	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
> 	at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
> 	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
> 	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725)
> 	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
> 	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
> 	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
> 	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
> 	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
> 	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
> 	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
> 	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
> 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
> 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> Caused by: java.lang.IllegalArgumentException: Key used already or never filled
> 	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
> 	at it.auties.whatsapp.util.Validate.createThrowable(Validate.java:29)
> 	at it.auties.whatsapp.util.Validate.isTrue(Validate.java:14)
> 	at it.auties.whatsapp.util.Validate.isTrue(Validate.java:9)
> 	at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:166)
> 	at it.auties.whatsapp.crypto.SessionCipher.tryDecrypt(SessionCipher.java:152)
> 	at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:131)
> 	... 38 more
> ```
> 
> These exceptions are coming "randomly" in the application log. Not that big of an issue but:
> 
> * is it possible to fix this or how can I fix it?
> * Is there a way it is no longer written to a file, as this take unnecessary diskspace after a while?
> * Can we configure the way exceptions are treated?
> 
> Setup
> 
> * Spring boot 2.6.6
> * JDK 17.0.2
> * whatsappweb4j 3.0-RC11
> 
> _#Priority: Low_

Are the messages deserialized correctly though? Like can you read all incoming messages despite this exception? 
Custom exception handling is coming in the next update(aka tomorrow) btw

**Comment by GDB4J** [comment]
> Are the messages deserialized correctly though? Like can you read all incoming messages despite this exception?

Well, not tested so far.
Currently using only "api.sendMessage".

so even more reason to assume that this "default" shouldn't be a problem(or throws exceptions) right?

**Comment by Auties00** [comment]
> > Are the messages deserialized correctly though? Like can you read all incoming messages despite this exception?
> 
> Well, not tested so far. Currently using only "api.sendMessage".
> 
> so even more reason to assume that this "default" shouldn't be a problem(or throws exceptions) right?

So I was testing and it looks like the bot disconnects at some point, reconnects and throws those errors. Interesting

**Comment by Auties00** [comment]
Oh well, I played myself. I introduced this bug myself without even noticing it when I restructured the serialization process. I moved that logic inside a listener which was fired from a shutdown hook asynchronously. Obviously, this meant that the application couldn't serialize its data as running async operations while your application is shutting down is the perfect way to avoid running it. I'm fixing it rn and will test further to see if this fixes the problem

**Comment by Auties00** [comment]
> > Are the messages deserialized correctly though? Like can you read all incoming messages despite this exception?
> 
> Well, not tested so far. Currently using only "api.sendMessage".
> 
> so even more reason to assume that this "default" shouldn't be a problem(or throws exceptions) right?

Check version 3.0-RC12, it should fix it. Before you do, delete all of your existing sessions

**Comment by GDB4J** [comment]
Verified on verison "3.0-RC12," Seems fixed!
Thanks

**Comment by GDB4J** [comment]
Hi @Auties00 

This problems still exists on version
`<version>3.0-RC14</version>`

```
Grizzly(2) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
2022-07-06 23:25:59,516 |  INFO | Grizzly(2) | it.auties.whatsapp.api.ErrorHandler | Saved stacktrace at: /home/xxx/.whatsappweb4j/exceptions/1657142759516.txt
2022-07-06 23:25:59,516 | ERROR | Grizzly(2) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
```

Stacktrace:
```
java.util.NoSuchElementException: Cannot decrypt message: no suitable session found
        at it.auties.whatsapp.crypto.SessionCipher.lambda$decrypt$5(SessionCipher.java:137)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:137)
        at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:463)
        at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:411)
        at it.auties.whatsapp.socket.MessageHandler.lambda$decode$34(MessageHandler.java:361)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:361)
        at it.auties.whatsapp.socket.Socket.readMessage(Socket.java:288)
        at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:61)
        at it.auties.whatsapp.socket.Socket.handleNode(Socket.java:174)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at it.auties.whatsapp.socket.Socket.onBinary(Socket.java:169)
        at jdk.internal.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
        at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652)
        at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:560)
        at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800)
        at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
        at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
        at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
        at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

(I know i wrote this was fixed, but probly not)
Can you investigate this further?


Thanks in advance,
Kind regards,

**Comment by Auties00** [comment]
> Hi @Auties00
> 
> This problems still exists on version `<version>3.0-RC14</version>`
> 
> ```
> Grizzly(2) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
> 2022-07-06 23:25:59,516 |  INFO | Grizzly(2) | it.auties.whatsapp.api.ErrorHandler | Saved stacktrace at: /home/xxx/.whatsappweb4j/exceptions/1657142759516.txt
> 2022-07-06 23:25:59,516 | ERROR | Grizzly(2) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
> ```
> 
> Stacktrace:
> 
> ```
> java.util.NoSuchElementException: Cannot decrypt message: no suitable session found
>         at it.auties.whatsapp.crypto.SessionCipher.lambda$decrypt$5(SessionCipher.java:137)
>         at java.base/java.util.Optional.orElseThrow(Optional.java:403)
>         at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:137)
>         at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:463)
>         at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:411)
>         at it.auties.whatsapp.socket.MessageHandler.lambda$decode$34(MessageHandler.java:361)
>         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
>         at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:361)
>         at it.auties.whatsapp.socket.Socket.readMessage(Socket.java:288)
>         at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:61)
>         at it.auties.whatsapp.socket.Socket.handleNode(Socket.java:174)
>         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
>         at it.auties.whatsapp.socket.Socket.onBinary(Socket.java:169)
>         at jdk.internal.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
>         at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
>         at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652)
>         at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:560)
>         at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800)
>         at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
>         at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
>         at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
>         at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725)
>         at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
>         at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
>         at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
>         at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
>         at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
>         at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
>         at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
>         at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
>         at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
>         at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
>         at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
>         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
>         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
>         at java.base/java.lang.Thread.run(Thread.java:833)
> ```
> 
> (I know i wrote this was fixed, but probly not) Can you investigate this further?
> 
> Thanks in advance, Kind regards,

Does this happen when you don't restart a session? Does this happen in a particular moment?

**Comment by GDB4J** [comment]
@Auties00 
It does indeed happen when i'm not restarting, just starting fresh (new connection).
I have no idea where it's coming from. It looks random for me ... :-)

Also, saw this one appearing again:

```
ERROR | Thread-42701 | it.auties.whatsapp.api.ErrorHandler | Socket failure at ERRONEOUS_NODE
2022-07-07 17:26:58,589 |  INFO | Thread-42701 | it.auties.whatsapp.api.ErrorHandler | Saved stacktrace at: /home/xxx/.whatsappweb4j/exceptions/1657207618589.txt
2022-07-07 17:26:58,589 | ERROR | Thread-42701 | it.auties.whatsapp.api.ErrorHandler | Ignored failure
```
1657207618589.txt:
```
java.util.concurrent.TimeoutException: Node[description=iq, attributes={xmlns=w:p, to=s.whatsapp.net, id=01-7504, type=get}, content=[Node[description=ping]]] timed out: no response from WhatsApp
        at it.auties.whatsapp.model.request.Request.cancelTimedFuture(Request.java:51)
        at it.auties.whatsapp.model.request.Request.lambda$with$0(Request.java:42)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Auties00** [comment]
> @Auties00 It does indeed happen when i'm not restarting, just starting fresh (new connection). I have no idea where it's coming from. It looks random for me ... :-)
> 
> Also, saw this one appearing again:
> 
> ```
> ERROR | Thread-42701 | it.auties.whatsapp.api.ErrorHandler | Socket failure at ERRONEOUS_NODE
> 2022-07-07 17:26:58,589 |  INFO | Thread-42701 | it.auties.whatsapp.api.ErrorHandler | Saved stacktrace at: /home/xxx/.whatsappweb4j/exceptions/1657207618589.txt
> 2022-07-07 17:26:58,589 | ERROR | Thread-42701 | it.auties.whatsapp.api.ErrorHandler | Ignored failure
> ```
> 
> 1657207618589.txt:
> 
> ```
> java.util.concurrent.TimeoutException: Node[description=iq, attributes={xmlns=w:p, to=s.whatsapp.net, id=01-7504, type=get}, content=[Node[description=ping]]] timed out: no response from WhatsApp
>         at it.auties.whatsapp.model.request.Request.cancelTimedFuture(Request.java:51)
>         at it.auties.whatsapp.model.request.Request.lambda$with$0(Request.java:42)
>         at java.base/java.lang.Thread.run(Thread.java:833)
> ```

Working on it right now. It also looks random to me tho

**Comment by Auties00** [comment]
I have pushed a new version called RC15 which should have fixed this issue completly

**Comment by GDB4J** [comment]
@Auties00 
This is stil a issue

Version:
```<version>3.0-RC26</version>```

Seeing this on the application log
```
2022-10-14 21:13:49,505 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
2022-10-14 21:13:49,509 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
2022-10-14 21:13:49,513 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
2022-10-14 21:13:49,514 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
2022-10-14 21:13:49,518 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
2022-10-14 21:13:49,518 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
2022-10-14 21:13:49,526 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
2022-10-14 21:13:49,526 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
2022-10-14 21:13:49,532 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
2022-10-14 21:13:49,532 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
2022-10-14 21:13:49,537 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
2022-10-14 21:13:49,537 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
2022-10-14 21:13:49,543 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
2022-10-14 21:13:49,543 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
2022-10-14 21:13:49,548 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
2022-10-14 21:13:49,549 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
2022-10-14 21:13:49,552 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
2022-10-14 21:13:49,553 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
```
Seeing this on the console output log (*)
```
Oct 14 21:13:49 camera-tools camera.jar[49231]: java.lang.RuntimeException: Cannot decrypt message with type msg inside 32479712828:7@s.whatsapp.net from 32479712828:7@s.whatsapp.net
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:487)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:416)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.MessageHandler.lambda$decode$36(MessageHandler.java:370)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at java.base/java.lang.Iterable.forEach(Iterable.java:75)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:370)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.Socket.readMessage(Socket.java:296)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:65)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.Socket.handleNode(Socket.java:186)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at java.base/java.lang.Iterable.forEach(Iterable.java:75)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.Socket.onBinary(Socket.java:181)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at jdk.internal.reflect.GeneratedMethodAccessor253.invoke(Unknown Source)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at java.base/java.lang.Thread.run(Thread.java:833)
Oct 14 21:13:49 camera-tools camera.jar[49231]: Caused by: java.util.NoSuchElementException: Cannot decrypt message: no suitable session found
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.crypto.SessionCipher.lambda$decrypt$5(SessionCipher.java:137)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at java.base/java.util.Optional.orElseThrow(Optional.java:403)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:137)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:479)
Oct 14 21:13:49 camera-tools camera.jar[49231]: #011... 37 more
```
(multiple times)



(*)
How can i handle the exception logging, to log everything in my (spring boot) application log? (not to go on console log?)
Can't find anything about exception handling in the readme

Thanks for your support!

**Comment by Auties00** [comment]
> @Auties00 This is stil a issue
> 
> Version: `<version>3.0-RC26</version>`
> 
> Seeing this on the application log
> 
> ```
> 2022-10-14 21:13:49,505 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
> 2022-10-14 21:13:49,509 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
> 2022-10-14 21:13:49,513 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
> 2022-10-14 21:13:49,514 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
> 2022-10-14 21:13:49,518 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
> 2022-10-14 21:13:49,518 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
> 2022-10-14 21:13:49,526 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
> 2022-10-14 21:13:49,526 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
> 2022-10-14 21:13:49,532 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
> 2022-10-14 21:13:49,532 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
> 2022-10-14 21:13:49,537 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
> 2022-10-14 21:13:49,537 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
> 2022-10-14 21:13:49,543 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
> 2022-10-14 21:13:49,543 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
> 2022-10-14 21:13:49,548 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
> 2022-10-14 21:13:49,549 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
> 2022-10-14 21:13:49,552 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Socket failure at MESSAGE
> 2022-10-14 21:13:49,553 | ERROR | Grizzly(1) | it.auties.whatsapp.api.ErrorHandler | Ignored failure
> ```
> 
> Seeing this on the console output log (*)
> 
> ```
> Oct 14 21:13:49 camera-tools camera.jar[49231]: java.lang.RuntimeException: Cannot decrypt message with type msg inside 32479712828:7@s.whatsapp.net from 32479712828:7@s.whatsapp.net
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:487)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:416)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.MessageHandler.lambda$decode$36(MessageHandler.java:370)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at java.base/java.lang.Iterable.forEach(Iterable.java:75)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:370)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.Socket.readMessage(Socket.java:296)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:65)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.Socket.handleNode(Socket.java:186)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at java.base/java.lang.Iterable.forEach(Iterable.java:75)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.Socket.onBinary(Socket.java:181)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at jdk.internal.reflect.GeneratedMethodAccessor253.invoke(Unknown Source)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at java.base/java.lang.Thread.run(Thread.java:833)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: Caused by: java.util.NoSuchElementException: Cannot decrypt message: no suitable session found
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.crypto.SessionCipher.lambda$decrypt$5(SessionCipher.java:137)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at java.base/java.util.Optional.orElseThrow(Optional.java:403)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:137)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:479)
> Oct 14 21:13:49 camera-tools camera.jar[49231]: #011... 37 more
> ```
> 
> (multiple times)
> 
> (*) How can i handle the exception logging, to log everything in my (spring boot) application log? (not to go on console log?) Can't find anything about exception handling in the readme
> 
> Thanks for your support!

This is been tracked in https://github.com/Auties00/WhatsappWeb4j/issues/162 
For exception handling see Whatsapp.Options.errorHandler
