### ISSUE TITLE
not loading all the contacts in the store

### ISSUE THREAD

**Issue by tomlux** [Auties00/WhatsappWeb4j#168]
Hy,
it seems that not all of my contacts are loadsed in the API-store.
Running several times my code, it returns sometimes a contacts-store-size of 146, the othertime a size of 149.
I didn't made any changes in my contacts.

I'm sure that I have more than 500 contacts.
I also got the correct contacts-size with your api some times ago (+- 1 month, but was also sometimes randomly).

Here is my simple code which writes out the store size:
`
        api = Whatsapp.lastConnection(Whatsapp.Options.defaultOptions());
        api.addListener(new Listener() {
            @Override
            public void onChats() {
                System.out.println("api.store().chats().size() = " + api.store().chats().size());
            }

            @Override
            public void onContacts() {
                System.out.println("api.store().contacts().size() = " + api.store().contacts().size());
            }
        });
        api.connect().join();
`

I also deleted the .whatsappweb4j folders without success. I running on the MASTER version of your project.

**Comment by Auties00** [comment]
> Hy, it seems that not all of my contacts are loadsed in the API-store. Running several times my code, it returns sometimes a contacts-store-size of 146, the othertime a size of 149. I didn't made any changes in my contacts.
> 
> I'm sure that I have more than 500 contacts. I also got the correct contacts-size with your api some times ago (+- 1 month, but was also sometimes randomly).
> 
> Here is my simple code which writes out the store size: ` api = Whatsapp.lastConnection(Whatsapp.Options.defaultOptions()); api.addListener(new Listener() { @OverRide public void onChats() { System.out.println("api.store().chats().size() = " + api.store().chats().size()); }
> 
> ```
>         @Override
>         public void onContacts() {
>             System.out.println("api.store().contacts().size() = " + api.store().contacts().size());
>         }
>     });
>     api.connect().join();
> ```
> 
> `
> 
> I also deleted the .whatsappweb4j folders without success. I running on the MASTER version of your project.

I've never considered adding a check for consistency with the contacts list. Can you try to open the whatsapp web app and see how many contacts you receive to understand if the issue is with the api or with Whatsapp itself? I'll be back tomorrow from my vacation so hopefully I can look into it

**Comment by tomlux** [comment]
I checked it with the webapp.
I created a new group and counted the proposed contact list (or how can I check the contacts size?):
  over 200 contacts while arriving at the letter "F" (abc...f)
So surly over 500 contacts, I think to remind me to that the api reporeted me some times ago over  800 contacts.

**Comment by Auties00** [comment]
> I checked it with the webapp. I created a new group and counted the proposed contact list (or how can I check the contacts size?): over 200 contacts while arriving at the letter "F" (abc...f) So surly over 500 contacts, I think to remind me to that the api reporeted me some times ago over 800 contacts.

Uhm okay, then probably i bricked it in a previous commit and didn't notice as there is no unit test for that

**Comment by tomlux** [comment]
If you give me an hint where you have to check for the consistency with the contacts list, maybe I can investigate some time on it

**Comment by Auties00** [comment]
> If you give me an hint where you have to check for the consistency with the contacts list, maybe I can investigate some time on it

Yeah sorry I'm still not home, that's why i haven't fixed it yet. You could use older versions to see the latest one that was working so it should be easier to find the issue

**Comment by tomlux** [comment]
Hy,
the **version 3.0-RC12** is the last version which is loading **correctly** my 755 contacts.
The versons after that are only loading around 150 contacts (sometimes 145, sometimes 149, ...)

**Comment by Auties00** [comment]
> Hy, the **version 3.0-RC12** is the last version which is loading **correctly** my 755 contacts. The versons after that are only loading around 150 contacts (sometimes 145, sometimes 149, ...)

So I've looked into it, but I can't seem to understand why this happens. I'll try to have it fixed by tomorrow night

**Comment by Auties00** [comment]
> Hy, the **version 3.0-RC12** is the last version which is loading **correctly** my 755 contacts. The versons after that are only loading around 150 contacts (sometimes 145, sometimes 149, ...)

I cannot figure out where the error comes from. I can look into it better tomorrow, if you find anything lmk

**Comment by Auties00** [comment]
Should be fixed in RC19, please lmk

**Comment by tomlux** [comment]
sorry, but still not loading all the data .
No errors, no exceptions, but still not loading everything...

with version RC19:
  api.store().contacts().size() = 192
  api.store().chats().size() = 354

with version RC12:
  api.store().contacts().size() = 767
  api.store().chats().size() = 1083

**Comment by Auties00** [comment]
> sorry, but still not loading all the data . No errors, no exceptions, but still not loading everything...
> 
> with version RC19: api.store().contacts().size() = 192 api.store().chats().size() = 354
> 
> with version RC12: api.store().contacts().size() = 767 api.store().chats().size() = 1083

Wait have you created a new session tho? Please use a new one because the last version was broken

**Comment by tomlux** [comment]
yes, deleted all the directories in .whatsappweb4j:

tried again with version RC19:
api.store().contacts().size() = 199
api.store().chats().size() = 358

**Comment by Auties00** [comment]
> yes, deleted all the directories in .whatsappweb4j:
> 
> tried again with version RC19: api.store().contacts().size() = 199 api.store().chats().size() = 358

wait can you try to compile the master branch and test it out? If it doesn't work I'll look into it

**Comment by tomlux** [comment]
already did that, I was doing the test using latest master brach. sorry

**Comment by Auties00** [comment]
> already did that, I was doing the test using latest master brach. sorry

Try RC24

**Comment by tomlux** [comment]
NO :-(
api.store().chats().size() = 378
api.store().contacts().size() = 202

deleted the session folder and used latest GIT version (RC24)

**Comment by Auties00** [comment]
> NO :-( api.store().chats().size() = 378 api.store().contacts().size() = 202
> 
> deleted the session folder and used latest GIT version (RC24)

Can u try my latest commit? I've counted the contacts and they look right to me now

**Comment by tomlux** [comment]
NO, still not loading allthe contact:
api.store().chats().size() = 378
api.store().contacts().size() = 204

I updated to latest commit and deleted the exisiting session folder. I did a cleaned test.

Any further runs after the first run with 378 chats and 204 contacts, I'm always getting:
api.store().chats().size() = 0
api.store().contacts().size() = 204

**Comment by Auties00** [comment]
> NO, still not loading allthe contact: api.store().chats().size() = 378 api.store().contacts().size() = 204
> 
> I updated to latest commit and deleted the exisiting session folder. I did a cleaned test.
> 
> Any further runs after the first run with 378 chats and 204 contacts, I'm always getting: api.store().chats().size() = 0 api.store().contacts().size() = 204

Yeah it's a beta commit, it's not Reading the chats. Tho it makes no sense, can you check if the contacts that are different from the older version aren't duplicates or something?

**Comment by tomlux** [comment]
the old version return correctly the 700 contacts, not duplicates

**Comment by Auties00** [comment]
> the old version return correctly the 700 contacts, not duplicates

Just thought about it, the contacts in the old version all have a name? I'm thinking that maybe the thing that changed is that a contact is no longer created if you don't have it saved with a name

**Comment by tomlux** [comment]
All the contacts have a name, but I never created a direct chat with them.
Most of them are only members in a group.

**Comment by Auties00** [comment]
> All the contacts have a name, but I never created a direct chat with them. Most of them are only members in a group.

Can you check if the only field filled is chosenName?

**Comment by tomlux** [comment]
I have 575 contacts with "null" in chosenName and 200 with a value in chosenName.
Seem that you identified the problem 👍 

The 575 contacts with "null" in chosenName have also null-values for "shortName", "lastKnownPresence" and "lastSeen". Also the fields "fullName" and of course "jid" are filled with values in the RC12-version.

**Comment by Auties00** [comment]
> I have 575 contacts with "null" in chosenName and 200 with a value in chosenName. Seem that you identified the problem 👍
> 
> The 575 contacts with "null" in chosenName have also null-values for "shortName", "lastKnownPresence" and "lastSeen". Only the fields "fullName" and of course "jid" are filled with values in the RC12-version.

Uhm maybe we are close to a fix then, I'll look into it

**Comment by Auties00** [comment]
Legit this is probably fixed by now

**Comment by tomlux** [comment]
hmm, it's now only loading 126 contacts with the latest git version.
I deleted the .whatsapp4j folder before running it.
Also after several running, it only load 126 contacts.

Here my code:
>        Whatsapp api = Whatsapp.lastConnection(Whatsapp.Options.defaultOptions()
>                        .qrHandler(qr -> System.out.println("qr = " + qr)))
>              .addLoggedInListener(() -> System.out.println("Connected"))
>              .addContactsListener((contacts) -> System.out.printf("listener_Contacts: %s%n", contacts.size()))
>              .addChatsListener(chats -> System.out.printf("listener_Chats: %s%n", chats.size()))
>              .connect()
>              .join();

The output is:
>        Connected
>        listener_Chats: 490
>        listener_Contacts: 126

**Comment by Auties00** [comment]
> hmm, it's now only loading 126 contacts with the latest git version. I deleted the .whatsapp4j folder before running it. Also after several running, it only load 126 contacts.
> 
> Here my code:
> 
> > ```
> >    Whatsapp api = Whatsapp.lastConnection(Whatsapp.Options.defaultOptions()
> >                    .qrHandler(qr -> System.out.println("qr = " + qr)))
> >          .addLoggedInListener(() -> System.out.println("Connected"))
> >          .addContactsListener((contacts) -> System.out.printf("listener_Contacts: %s%n", contacts.size()))
> >          .addChatsListener(chats -> System.out.printf("listener_Chats: %s%n", chats.size()))
> >          .connect()
> >          .join();
> > ```
> 
> The output is:
> 
> > ```
> >    Connected
> >    listener_Chats: 490
> >    listener_Contacts: 126
> > ```

Can you try to see if in the Whatsapp options the history length is set to one year or 3 months? Maybe that's it

**Comment by tomlux** [comment]
Hi,
I have configured the history length to 1 year, same result.

What I noticed on the first run (after deleteing the whatsapp4j folder):
  the addLoggedInListener is  called and also the addChatsListener 
  but **the addContactsListener() is never called**.

Only on the secong run (whith an existing whatsapp4j  folder), the addContactsListener is called.

**Comment by Auties00** [comment]
> Hi, I have configured the history length to 1 year, same result.
> 
> What I noticed on the first run (after deleteing the whatsapp4j folder): the addLoggedInListener is called and also the addChatsListener but **the addContactsListener() is never called**.
> 
> Only on the secong run (whith an existing whatsapp4j folder), the addContactsListener is called.

This is fixed in the master branch.
The problem right now is that on my phone all the contacts are synced(it even syncs 26 more than RC12).
This is why this issue is kind of confusing, can you identify using a debugger the method that calls the addContact method?

**Comment by tomlux** [comment]
Hy, I checked this issue today against the latest git version.
It's now loading all the contacts

> api.store().chats().size() = 884
> api.store().contacts().size() = 807

We can close this issue. Thanks
