### ISSUE TITLE
Add support for multi device beta

### ISSUE THREAD

**Issue by Auties00** [Auties00/WhatsappWeb4j#37]
WhatsappWeb now supports a standalone mode called multi-device mode. Add support for it asap

**Comment by EliyahuStern** [comment]
@Auties00 does this means support for connecting with multiple accounts in parallel? Is the related PR ready for experiments? Anything I can do to help move such capability forward?

**Comment by Auties00** [comment]
> @Auties00 does this means support for connecting with multiple accounts in parallel? Is the related PR ready for experiments? Anything I can do to help move such capability forward?

it will be included, but I'm not done yet. I'm not really sure about what you can do to speed up the development process though

**Comment by zhengshengjie666** [comment]
您好，多设备版本怎么运行？二维码不能扫码

**Comment by yhtsnda** [comment]
@Auties00 hi
What is the current status of the multi-device version,  scan the qrcode to login and send and receive messages normally?

**Comment by Auties00** [comment]
> @Auties00 hi What is the current status of the multi-device version, scan the qrcode to login and send and receive messages normally?

You can receive messages and change some settings. I'm working on message sending

**Comment by yhtsnda** [comment]
> > @Auties00 hi What is the current status of the multi-device version, scan the qrcode to login and send and receive messages normally?
> 
> You can receive messages and change some settings. I'm working on message sending

thks, great job!

**Comment by PatrickMSM** [comment]
How much is done yet of the multi-device version? Also, is there an ETA for when it will be finished?

**Comment by Auties00** [comment]
> How much is done yet of the multi-device version? Also, is there an ETA for when it will be finished?

I'm stuck on message sending, everything else works

**Comment by iileandro** [comment]
Hi.

I'm trying to run the branch ''multidevicebeta", but i'm stuck on three dependencies. I think they are only local for you. Could you share the snapshots?

![image](https://user-images.githubusercontent.com/17341676/157328397-171d0da9-2922-484b-8748-ee1131e4ede8.png)

I also would like to help. Is it possible to help in this mission?

**Comment by Auties00** [comment]
> Hi.
> 
> I'm trying to run the branch ''multidevicebeta", but i'm stuck on three dependencies. I think they are only local for you. Could you share the snapshots?
> 
> ![image](https://user-images.githubusercontent.com/17341676/157328397-171d0da9-2922-484b-8748-ee1131e4ede8.png)
> 
> I also would like to help. Is it possible to help in this mission?

Yeah, as soon as I'll get home I'll release them on maven central so you can run it

**Comment by Auties00** [comment]
> Hi.
> 
> I'm trying to run the branch ''multidevicebeta", but i'm stuck on three dependencies. I think they are only local for you. Could you share the snapshots?
> 
> ![image](https://user-images.githubusercontent.com/17341676/157328397-171d0da9-2922-484b-8748-ee1131e4ede8.png)
> 
> I also would like to help. Is it possible to help in this mission?

Done

**Comment by Auties00** [comment]
> Hi.
> 
> I'm trying to run the branch ''multidevicebeta", but i'm stuck on three dependencies. I think they are only local for you. Could you share the snapshots?
> 
> ![image](https://user-images.githubusercontent.com/17341676/157328397-171d0da9-2922-484b-8748-ee1131e4ede8.png)
> 
> I also would like to help. Is it possible to help in this mission?

So you can defenitely help but i'm a mad man and designed practically everything myself. The problem currently is in message sending and considering that I implemented the whole signal protocol I don't know if the bug is there or in the data that I'm supplying it with. I've been debugging for some days and fixed so many issues, but messages still only arrive as "This message may take a while"

**Comment by iileandro** [comment]
I decided to learn more about GoLang to adapt a rest app over [the whatsmewow version](https://github.com/tulir/whatsmeow). It already has multidevice support. So now I solved my issue. I think I couldn't help inside those core whatsapp implementations. I would need to study too much to get some way to help.

**Comment by jefaokpta** [comment]
@Auties00  I have follow this thread like a novel. 
I saw your last commit:  Message encoding is still not working, starting to lose faith.
I don't have the ability to help so I'm rooting for you 👊🏼.
So far I'm using a node lib https://github.com/adiwajshing/Baileys, it's not great but multi device is working.

**Comment by Auties00** [comment]
> @Auties00 I have follow this thread like a novel. I saw your last commit: Message encoding is still not working, starting to lose faith. I don't have the ability to help so I'm rooting for you 👊🏼. So far I'm using a node lib https://github.com/adiwajshing/Baileys, it's not great but multi device is working.

This project is definitely driving me crazy, but I'm happy that people are following this journey. It's definitely taking much more than expected, but I'm confident that I'll complete the project. It's honestly a lot of work though because I made some choices along the way that increased the work size by a lot, but they should at least make the library a joy to use once it's finished

**Comment by Tiebe** [comment]
@Auties00 Trying to build the latest commit but it's giving me the error that "the jar will be empty - no content marked for inclusion" while running mvn install. Here is a bit of the log and [click here](https://termbin.com/3mfv) to see the full log.

```
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ whatsappweb4j ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ whatsappweb4j ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ whatsappweb4j ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ whatsappweb4j ---
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ whatsappweb4j ---
[WARNING] JAR will be empty - no content was marked for inclusion!
```

**Comment by Auties00** [comment]
> @Auties00 Trying to build the latest commit but it's giving me the error that "the jar will be empty - no content marked for inclusion" while running mvn install. Here is a bit of the log and [click here](https://termbin.com/3mfv) to see the full log.
> 
> ```
> [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ whatsappweb4j ---
> [INFO] No sources to compile
> [INFO] 
> [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ whatsappweb4j ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 5 resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ whatsappweb4j ---
> [INFO] No sources to compile
> [INFO] 
> [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ whatsappweb4j ---
> [INFO] 
> [INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ whatsappweb4j ---
> [WARNING] JAR will be empty - no content was marked for inclusion!
> ```
> 
> EDIT: Fixed this. You need to replace every backslash () with a normal slash (/) on Linux and Mac. You should probably fix this @Auties00

Thanks for the heads up. If you want you can open a pr if you have already fixed it

**Comment by Tiebe** [comment]
> > @Auties00 Trying to build the latest commit but it's giving me the error that "the jar will be empty - no content marked for inclusion" while running mvn install. Here is a bit of the log and [click here](https://termbin.com/3mfv) to see the full log.
> > ```
> > [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ whatsappweb4j ---
> > [INFO] No sources to compile
> > [INFO] 
> > [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ whatsappweb4j ---
> > [INFO] Using 'UTF-8' encoding to copy filtered resources.
> > [INFO] Copying 5 resources
> > [INFO] 
> > [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ whatsappweb4j ---
> > [INFO] No sources to compile
> > [INFO] 
> > [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ whatsappweb4j ---
> > [INFO] 
> > [INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ whatsappweb4j ---
> > [WARNING] JAR will be empty - no content was marked for inclusion!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > EDIT: Fixed this. You need to replace every backslash () with a normal slash (/) on Linux and Mac. You should probably fix this @Auties00
> 
> Thanks for the heads up. If you want you can open a pr if you have already fixed it

Done!

**Comment by PatrickMSM** [comment]
@Auties00 you should take a look at how other APIs do it (like [Baileys](https://github.com/adiwajshing/Baileys)) and try replicating it in Java

**Comment by Auties00** [comment]
> @Auties00 you should take a look at how other APIs do it (like [Baileys](https://github.com/adiwajshing/Baileys)) and try replicating it in Java

That's not the issue, I've already reversed it myself and doubled checked it with baileys and even though the ciphered message is exactly the same, it just doesn't seem to work. That's the problem I'm trying to solve

**Comment by PatrickMSM** [comment]
> > @Auties00 you should take a look at how other APIs do it (like [Baileys](https://github.com/adiwajshing/Baileys)) and try replicating it in Java
> 
> That's not the issue, I've already reversed it myself and doubled checked it with baileys and even though the ciphered message is exactly the same, it just doesn't seem to work. That's the problem I'm trying to solve

If you don't mind me asking, what's not working?

**Comment by Auties00** [comment]
> > > @Auties00 you should take a look at how other APIs do it (like [Baileys](https://github.com/adiwajshing/Baileys)) and try replicating it in Java
> > 
> > 
> > That's not the issue, I've already reversed it myself and doubled checked it with baileys and even though the ciphered message is exactly the same, it just doesn't seem to work. That's the problem I'm trying to solve
> 
> If you don't mind me asking, what's not working?

In modern protobuf or this library?

**Comment by asabadyr** [comment]
Hi @Auties00 looks like protoc-1.10 snapshot is not released. Can you please make it available or we may stick with 1.9 version for now? In your pom.xml you are referring to a newer version.
Also please let me know if you need help with encoding outbound messages.

**Comment by mansoordeep** [comment]
WhatsApp had made it live it seems. No longer it's beta. No option to disable as well..

**Comment by Auties00** [comment]
Btw for anyone that missed it, I got messages to work finally. I should finish the whole feature in a couple of days hopefully

**Comment by Tiebe** [comment]
> I should finish the whole feature in a couple of days hopefully
Have you had time to finish it yet?

**Comment by EliyahuStern** [comment]
> Hi @Auties00 looks like protoc-1.10 snapshot is not released. Can you please make it available? In your pom.xml you are referring to a newer version. 1.9 version is missing it.auties.protobuf.encoder.ProtobufValueProvider Also map-module 1.1-snapshot is not available. Also please let me know if you need help with encoding outbound messages.

@asabadyr I believe you should clone https://github.com/Auties00/MapModule and `mvn clean install` it to resolve this.

**Comment by Auties00** [comment]
> @Auties00 can you give some hints on where you are on this? I see that when running ApiTest I am able to send messages, but only my connected device receives them while the receiver sees "Waiting for this message. This may take a while.". I guess there's some voting protocol that needs confirmation from other devices to proceed. How can I debug this? Should I try to use https://github.com/Auties00/WhatsappWebRequestAnalyzer?
> 
> The links in [this page](https://faq.whatsapp.com/general/security-and-privacy/seeing-waiting-for-this-message-this-may-take-a-while-business/?lang=en) seems like a good place for me to start. Let me know if you are aware of better resources.

I've just fixed messages in the latest commit, though you'll need a new version of modern protobuf and the map module that i haven't published yet. A release should be ready in a week

**Comment by EliyahuStern** [comment]
Just making sure you are aware of a few issues:
1. Non English (in my case Hebrew) and other unicode emojis does not work.
2. `lastConnection()` keeps throwing so I need to scan a QR every time.
3. The library cannot decrypt messages I send and receive from other devices.
4. Cannot send messages to JID with phone number, only by contact names.
Let me know if you need any logs.

**Comment by Auties00** [comment]
> Just making sure you are aware of a few issues:
> 
> 1. Non English (in my case Hebrew) and other unicode emojis does not work.
> 2. `lastConnection()` keeps throwing so I need to scan a QR every time.
> 3. The library cannot decrypt messages I send and receive from other devices.
> 4. Cannot send messages to JID with phone number, only by contact names.
>    Let me know if you need any logs.

So for the first issue, I have no idea how to fix it, any suggestions?
The second issue has been fixed in version 3.0-RC1
The third issue should also have been fixed in 3.0-RC1
Can you show me what you mean by the fourth one? Thanks
